server:
  port: 8099
  
#SpringBoot 및 DB 설정   
spring:
  data:
    rest:
      base-path: /api
  datasource:
#hikari
    hikari:
      idle-timeout: 300
      max-lifetime: 300
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://192.168.0.2:3308/elasticworks?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#      192.168.0.2:3308
      username: elkwks
      password: 1234
      connection-test-query: SELECT NOW() FROM dual
  devtools: 
    livereload:
      enabled: true
  cache:
    type: redis
#Redis 
  redis:
    host: 192.168.0.2
    password: 1q2w3e4r
    port: 6379
    lettuce:
     pool:
       max-active: 10
       max-idle: 10 
       min-idle: 2
# 콘솔 창에 출력되는 로깅 메세지를 색으로 구분해서 출력
  output:
    ansi:
      enabled: always
      
#MyBatis      
mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: kr.co.elasticworks.api.domain
  

  


